"""답변 품질이 기준 미달(Faithfulness 미달)이거나 해결 불가능한 질문일 경우,
담당자(CSM/Support) 전달용 티켓 리포트를 영문으로 자동 생성하는 로직."""
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import List, Optional

from langchain_core.documents import Document

from app.core.faithfulness import FaithfulnessResult
from app.core.prompts import NO_ANSWER_PHRASE_EN, NO_ANSWER_PHRASE_KO

REASON_UNRESOLVABLE = "unresolvable"
REASON_LOW_FAITHFULNESS = "low_faithfulness"

_REASON_LABELS = {
    REASON_UNRESOLVABLE: "No supporting documentation found for this question",
    REASON_LOW_FAITHFULNESS: "AI-generated answer did not pass the faithfulness check",
}

_NEXT_STEPS = {
    REASON_UNRESOLVABLE: [
        "Verify whether existing documentation actually covers this topic.",
        "If not, route to the docs/content team to add coverage.",
        "Reply to the customer directly with a manually verified answer.",
    ],
    REASON_LOW_FAITHFULNESS: [
        "Review the AI draft answer against the retrieved sources below before using it.",
        "Correct or remove any unsupported claims listed below.",
        "Reply to the customer with a verified answer.",
    ],
}


def is_unresolvable_answer(answer: str) -> bool:
    """답변이 '문서에서 확인 불가' 정형 문구(한/영)와 정확히 일치하는지 확인한다.

    시스템 프롬프트는 한국어/영어 외의 언어에 대해서는 고정 문구 없이 자연스러운 번역을
    요구하므로, 그 경우는 이 함수로 잡히지 않고 대신 Faithfulness 평가 경로로 보완된다.
    """
    normalized = answer.strip()
    return normalized in (NO_ANSWER_PHRASE_KO, NO_ANSWER_PHRASE_EN)


@dataclass
class TicketReport:
    ticket_id: str
    created_at: str  # UTC, human-readable
    escalation_reason: str  # REASON_UNRESOLVABLE | REASON_LOW_FAITHFULNESS
    priority: str  # "Normal" | "High"
    customer_question: str
    ai_draft_answer: str
    referenced_sources: List[str] = field(default_factory=list)
    faithfulness_score: Optional[float] = None
    unsupported_claims: List[str] = field(default_factory=list)
    faithfulness_reasoning: str = ""

    def to_text(self) -> str:
        """CSM/Support 담당자에게 그대로 전달 가능한 영문 플레인텍스트 리포트를 만든다."""
        lines = [
            "=" * 64,
            "SUPPORT TICKET — AUTO-GENERATED BY RAG AGENT (NEEDS HUMAN REVIEW)",
            "=" * 64,
            f"Ticket ID       : {self.ticket_id}",
            f"Created At (UTC): {self.created_at}",
            f"Priority        : {self.priority}",
            f"Escalation Reason: {_REASON_LABELS.get(self.escalation_reason, self.escalation_reason)}",
            "",
            "-- Customer Question " + "-" * 42,
            self.customer_question,
            "",
            "-- AI Draft Answer (reference only, NOT verified) " + "-" * 12,
            self.ai_draft_answer,
            "",
        ]

        if self.faithfulness_score is not None:
            lines.append("-- Faithfulness Check " + "-" * 41)
            lines.append(f"Score: {self.faithfulness_score:.2f} (below threshold)")
            if self.faithfulness_reasoning:
                lines.append(f"Judge reasoning: {self.faithfulness_reasoning}")
            if self.unsupported_claims:
                lines.append("Unsupported claims:")
                lines.extend(f"  - {c}" for c in self.unsupported_claims)
            lines.append("")

        lines.append("-- Retrieved Sources " + "-" * 42)
        if self.referenced_sources:
            lines.extend(f"  - {s}" for s in self.referenced_sources)
        else:
            lines.append("  (none retrieved)")
        lines.append("")

        lines.append("-- Recommended Next Steps " + "-" * 37)
        steps = _NEXT_STEPS.get(self.escalation_reason, [])
        lines.extend(f"  {i}. {step}" for i, step in enumerate(steps, start=1))
        lines.append("=" * 64)
        return "\n".join(lines)


def build_ticket_report(
    question: str,
    answer: str,
    chunks: List[Document],
    faithfulness_result: Optional[FaithfulnessResult] = None,
    now: Optional[datetime] = None,
) -> TicketReport:
    """Faithfulness 미달 또는 해결 불가능한 질문에 대해 CSM/Support 전달용 티켓 리포트를 생성한다."""
    reason = REASON_UNRESOLVABLE if is_unresolvable_answer(answer) else REASON_LOW_FAITHFULNESS
    priority = "Normal" if reason == REASON_UNRESOLVABLE else "High"

    sources = []
    for chunk in chunks:
        source = chunk.metadata.get("source", "unknown")
        section = chunk.metadata.get("h1") or chunk.metadata.get("h2") or chunk.metadata.get("h3")
        label = f"{source} / {section}" if section else source
        if label not in sources:
            sources.append(label)

    faithfulness_score = None
    faithfulness_reasoning = ""
    unsupported_claims: List[str] = []
    if faithfulness_result is not None:
        faithfulness_score = faithfulness_result.score
        faithfulness_reasoning = faithfulness_result.reasoning
        unsupported_claims = [c.claim for c in faithfulness_result.unsupported_claims]

    created_at = (now or datetime.now(timezone.utc)).strftime("%Y-%m-%d %H:%M:%S UTC")

    return TicketReport(
        ticket_id=f"TCK-{uuid.uuid4().hex[:8].upper()}",
        created_at=created_at,
        escalation_reason=reason,
        priority=priority,
        customer_question=question,
        ai_draft_answer=answer,
        referenced_sources=sources,
        faithfulness_score=faithfulness_score,
        unsupported_claims=unsupported_claims,
        faithfulness_reasoning=faithfulness_reasoning,
    )
